version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'MoSsxmHdG9mXVw'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db/.docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
      
  backend:
    build:
      context: ./express-ts-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: mysql://ledgraph-backend-user:emL6Z5bPXBx86F@db:3306/ledgraph
      SESSION_SECRET: 7d77f882053d5e5f5a5e5d5b5c313233343536373839303132333435363738
    depends_on:
      - db

  frontend:
    build:
      context: ./react-ts-client
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:3000/api
      CHOKIDAR_USEPOLLING: 'true'

volumes:
  db_data: