version: '3'

services:
  express-server:
    build:
      context: ./express-ts-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: mysql://myuser:mypassword@mysql:3306/ledgraph
    depends_on:
      - mysql
    command: /bin/sh -c "./wait-for-it.sh mysql:3306 --timeout=30 && sleep 5 && npx prisma generate && npx prisma migrate deploy && nodemon -L --watch 'src/**/*.ts' --exec 'ts-node' src/index.ts"
    volumes:
      - ./express-ts-server:/usr/src/app

  react-client:
    build:
      context: ./react-ts-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-ts-client:/usr/src/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: ledgraph
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
