CREATE DATABASE IF NOT EXISTS ledgraph;

CREATE USER 'ledgraph-backend-user'@'%' IDENTIFIED BY 'emL6Z5bPXBx86F';

GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `ledgraph`.* TO 'ledgraph-backend-user'@'%';

FLUSH PRIVILEGES;
